openapi: 3.0.0

info:
 version: '1.0'
 title: 'LBAW ProjectSync'
 description: 'Web Resources Specification (A7) for ProjectSync'

servers:
- url: http://lbaw2363.lbaw.fe.up.pt
  description: Production server

tags:
 - name: 'M01: Static Pages'
 - name: 'M02: Authentication and Individual Profile'
 - name: 'M03: Project Area'
 - name: 'M04: Administration'

paths:
#-------------------------------- M01 -----------------------------------------
  /:
    get:
      operationId: R101
      summary: 'R101: See the home page'
      description: 'See the home page when you access the website. Access: PUB'
      tags:
      - 'M01: Static Pages'
      responses:
       '200':
        description: 'Ok. Show homepage' 

  /about-us/:
    get:
      operationId: R102
      summary: 'R102: See About Us'
      description: 'Provide description about the website and its creators. Access: PUB'
      tags:
      - 'M01: Static Pages'
      responses:
       '200':
        description: 'Ok. Show About Us page' 
 
  /faq/:
    get:
      operationId: R103
      summary: 'R103: See Frequently Asked Questions (FAQ)'
      description: 'Provide frequently asked questions about our website. Access: PUB'
      tags:
      - 'M01: Static Pages'
      responses:
       '200':
        description: 'Ok. Show the FAQ page'

#-------------------------------- M02 -----------------------------------------

  /login:
    get:
     operationId: R201
     summary: 'R201: Login Form'
     description: 'Provide login form. Access: PUB'
     tags:
       - 'M02: Authentication and Individual Profile'
     responses:
       '200':
         description: 'Ok. Show Log-in UI'
    post:
     operationId: R202
     summary: 'R202: Login Action'
     description: 'Processes the login form submission. Access: PUB'
     tags:
       - 'M02: Authentication and Individual Profile'

     requestBody:
       required: true
       content:
         application/x-www-form-urlencoded:
           schema:
             type: object
             properties:
               email:          # <!--- form field name
                 type: string
               password:    # <!--- form field name
                 type: string
             required:
                  - email
                  - password

     responses:
       '302':
         description: 'Redirect after processing the login credentials.'
         headers:
           Location:
             schema:
               type: string
             examples:
               302Success:
                 description: 'Successful authentication. Redirect to projects page.'
                 value: '/projects'
               302Error:
                 description: 'Failed authentication. Redirect to login form.'
                 value: '/login'

  /logout:
    post:
     operationId: R203
     summary: 'R203: Logout Action'
     description: 'Logout the current authenticated user. Access: USR, ADM'
     tags:
       - 'M02: Authentication and Individual Profile'
     responses:
       '302':
         description: 'Redirect after processing logout.'
         headers:
           Location:
             schema:
               type: string
             examples:
               302Success:
                 description: 'Successful logout. Redirect to login form.'
                 value: '/login'

  /register:
    get:
     operationId: R204
     summary: 'R204: Register Form'
     description: 'Provide new user registration form. Access: PUB'
     tags:
       - 'M02: Authentication and Individual Profile'
     responses:
       '200':
         description: 'Ok. Show Sign-Up UI'

    post:
     operationId: R205
     summary: 'R205: Register Action'
     description: 'Processes the new user registration form submission. Access: PUB'
     tags:
       - 'M02: Authentication and Individual Profile'

     requestBody:
       required: true
       content:
         application/x-www-form-urlencoded:
           schema:
             type: object
             properties:
               name:
                 type: string
               username:
                 type: string
               email:
                 type: string
               password:
                 type: string
               repeat_password:
                 type: string
             required:
                - name
                - username
                - email
                - password
                - repeat_password

     responses:
       '302':
         description: 'Redirect after processing the new user information.'
         headers:
           Location:
             schema:
               type: string
             examples:
               302Success:
                 description: 'Successful authentication. Redirect to projects page.'
                 value: '/projects'
               302Failure:
                 description: 'Failed authentication. Redirect to register form.'
                 value: '/register'

  /profile/{username}:
   get:
     operationId: R206
     summary: 'R206: View user profile'
     description: 'Show the individual user profile. Access: USR'
     tags:
       - 'M02: Authentication and Individual Profile'

     parameters:
       - in: path
         name: username
         schema:
           type: string
         required: true

     responses:
       '200':
         description: 'Ok. Show User Profile UI'

  /profile/{username}/edit:
    get:
      operationId: R207
      summary: 'R207: Get user profile form'
      description: 'Show the individual user profile edit form. Access: OWN'
      tags:
        - 'M02: Authentication and Individual Profile'
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 'Ok. Show edit profile UI'
    post:
      operationId: R208
      summary: 'R208: Edit Profile Action'
      description: 'Allows a user to edit his information. Access: OWN'
      tags:
        - 'M02: Authentication and Individual Profile'
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                email:
                  type: string
                bio:
                  type: string
      responses:
        '302':
          description: 'Redirect member after editing profile.'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'User information edited successfully. Redirects user to their profile page.'
                  value: '/user/{username}'
                302Failure:
                  description: 'User information editing failed. Stay in edit page.'
                  value: '/user/{username}/edit'
  /change_password:
    get:
      operationId: R209
      summary: 'R209: Get user password edit form'
      description: 'Show the individual user password edit form. Access: OWN'
      tags:
        - 'M02: Authentication and Individual Profile'
      responses:
        '200':
          description: 'Ok. Show edit password UI'

    post:
      operationId: R210
      summary: 'R210: Change user password'
      description: Change the user's password.
      tags:
        - 'M02: Authentication and Individual Profile'
      requestBody:
        description: New password data
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                old_password:
                  type: string
                new_password:
                  type: string
                repeat_new_password:
                  type: string
              required:
                - old_password
                - new_password
                - repeat_new_password
      responses:
        '302':
          description: 'Redirect member after editing their password.'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'Password edited successfully. Redirects user to their profile page.'
                  value: '/user/{username}'
                302Failure:
                  description: 'Password editing failed. Stay in edit page.'
                  value: '/change_password'
  
  /delete_user:
    get:
      operationId: R211
      summary: 'R211: Delete user'
      description: 'Delete user. Access: OWN'
      tags:
        - 'M02: Authentication and Individual Profile'
      responses:
        '200':
          description: 'Ok. User has been deleted'

#-------------------------------- M03 -----------------------------------------

  /projects:
    get:
     operationId: R301
     summary: 'R301: Projects'
     description: 'Projects page. Access: USR'
     tags:
       - 'M03: Project Area'
     responses:
       '200':
         description: 'Ok. Show Projects page'
  
  /createProject:
    get:
     operationId: R302
     summary: 'R302: Get Projects Creation Page'
     description: 'Get Projects page. Access: USR'
     tags:
       - 'M03: Project Area'
     responses:
       '200':
         description: 'Ok. Show project creator form'
    
    post:
      operationId: R303
      summary: 'R303: Create a project'
      description: 'Create a project. Access: USR'
      tags:
        - 'M03: Project Area'
      requestBody:
       required: true
       content:
         application/x-www-form-urlencoded:
           schema:
             type: object
             properties:
               name:
                 type: string
               deliveryDate:
                 type: string
             required:
                - name
      responses:
       '302':
         description: 'Redirect after processing the project information.'
         headers:
           Location:
             schema:
               type: string
             examples:
               302Success:
                 description: 'Successful creation. Redirect to projects page.'
                 value: '/project/{project_id}/'
               302Failure:
                 description: 'Failed creation. Redirect to create project form.'
                 value: '/createProject'

  /projects/{project_id}/settings:
    get:
     operationId: R304
     summary: 'R304: Get Project settings Page'
     description: 'Get Projects settings page. Access: PC'
     tags:
       - 'M03: Project Area'
     parameters:
        - in: path
          name: projectId
          schema:
            type: string
          required: true
     responses:
       '200':
         description: 'Ok. Show project settings page'
    post:
      operationId: R305
      summary: 'R305: Change projects page'
      description: 'Create a project. Access: PC'
      tags:
        - 'M03: Project Area'
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
          required: true
      requestBody:
       required: true
       content:
         application/x-www-form-urlencoded:
           schema:
             type: object
             properties:
               name:
                 type: string
               deliveryDate:
                 type: string
      responses:
       '302':
         description: 'Redirect after processing the project information.'
         headers:
           Location:
             schema:
               type: string
             examples:
               302Success:
                 description: 'Successful edit. Redirect to projects page.'
                 value: '/project/{project_id}/'
               302Failure:
                 description: 'Failed edit. Redirect to edit form.'
                 value: '/project/{project_id}/settings'
  
  /projects/{project_id}/:
    get:
     operationId: R306
     summary: 'R306: Get Project Page'
     description: 'Get Projects page. Access: PM'
     tags:
       - 'M03: Project Area'
     parameters:
        - in: path
          name: projectId
          schema:
            type: string
          required: true
     responses:
       '200':
         description: 'Ok. Show project page'

  /projects/{project_id}/createTask:
    get:
     operationId: R307
     summary: 'R307: Get task creation page'
     description: 'Get task creation page. Access: PM'
     tags:
       - 'M03: Project Area'
     parameters:
        - in: path
          name: projectId
          schema:
            type: string
          required: true
     responses:
       '200':
         description: 'Ok. Show task creation page'
    post:
      operationId: R308
      summary: 'R308: Create a task'
      description: 'Create a task. Access: PM'
      tags:
        - 'M03: Project Area'
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
          required: true
      requestBody:
       required: true
       content:
         application/x-www-form-urlencoded:
           schema:
             type: object
             properties:
               name:
                 type: string
               description:
                 type: string
               deliveryDate:
                 type: string
               priority:
                 type: string
               task-members:
                 type: array
             required:
                - name
                - description
                - deliveryDate
                - priority
                - task-members
      responses:
       '302':
         description: 'Redirect after processing the task information.'
         headers:
           Location:
             schema:
               type: string
             examples:
               302Success:
                 description: 'Successful creation. Redirect to project page.'
                 value: '/project/{project_id}/'
               302Failure:
                 description: 'Failed creation. Redirect to create project form.'
                 value: '/project/{project_id}/createTask'

  /api/task/{id}:
    get:
      operationId: R308
      summary: "R308: Get task info"
      description: "Get the task's information. Access: PM"
      tags:
        - 'M03: Project Area'
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true

      responses:
        '200':
          description: 'Ok. Show task page UI'
          content:
            application/json:
              schema:
                type: array
    delete:
      operationId: R309
      summary: "R309: Delete task"
      description: "Delete a task. Access: PM"
      tags:
        - 'M03: Project Area'
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true

      responses:
        '200':
         description: 'Ok. Task deleted'
    post:
      operationId: R310
      summary: "R310: Update task info"
      description: "Update the task's information. Access: PM"
      tags:
        - 'M03: Project Area'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                members:
                  type: array
                deleveryDate:
                  type: string
                priority:
                  type: string
      responses:
        '200':
          description: 'Task updated'
#-------------------------------- M04 -----------------------------------------

  /adminPage:
    get:
      operationId: R401
      summary: 'R401: AdminPage'
      description: 'Get admin page. Access: ADM'
      tags:
      - 'M04: Administration'
      responses:
       '200':
        description: 'Ok. Show About Us page' 

  /block_user:
    post:
      operationId: R402
      summary: 'R402: Block or Unblock user'
      description: 'Block or Unblock user. Access: ADM'
      tags:
        - 'M04: Administration'
      responses:
        '200':
          description: 'Ok. User has been blocker or unblocked'